stages:
    # - build
    - deploy

# Build:
#     stage: build
#     cache:
#         paths:
#             - node_modules/
#     image: node:16.14.2
#     only:
#         - main
#     tags:
#         - global_stage
#     script:
#         - npm i
#         - npm run build:prod
#     artifacts:
#         paths:
#             - build/

Deploy:
    stage: deploy
    image: node:16.14.2
    # dependencies: 
    #     - Build
    tags:
        - stage
    before_script:
        - 'which ssh-agent || ( apt-get install -qq openssh-client )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
    script:
        - touch test.txt
        # - scp -r test.txt cp05609@87.249.43.162:/home/c/cp05609/morport/public_html/wp-content/themes/morport/static
        - ssh -o StrictHostKeyChecking=no cp05609@vh344.timeweb.ru "cd /home/c/cp05609/morport/public_html/wp-content/themes/morport/static;"

